### PR TITLE
chore: Set background Pancake Images

### PR DESCRIPTION
**Pull request by emmaodia**
Chore: Set the Background Images on the exchange index page. Figma here: https://www.figma.com/file/q5dKq3BuQZ4YzV5pR0Mt2M/Design-System-%2B-UI?node-id=167%3A24998

View on Netlify: https://6023e555d4ef075009ef1c4c--condescending-wescoff-cf566a.netlify.app/#/swap

Desktop View
pancakesvg

Mobile View
pancakesvgMobile

### CODE REVIEW

**Review by RabbitDoge — CHANGES_REQUESTED** [review]
The position is messed up on mobile.
Imo better use a background image rather the an img tag, it will be easier to position it. Even semantically it makes more sense.

**Comment by emmaodia** [comment]
> The position is messed up on mobile.
> Imo better use a background image rather the an img tag, it will be easier to position it. Even semantically it makes more sense.

Thank you for the Feedback @RabbitDoge Changes implemented. 

Task completed @Chef-Chungus

**Review by RabbitDoge — CHANGES_REQUESTED** [review]
Still not good.

image
This is how the pancake image show on middle screens. Please reposition based on breakpoints.

---

image
This is how the page looks like during the loading. Please apply a min height 100vh on the container with the background.

---

image
The arch doesn't seem correct according to our designer.

**Comment by emmaodia** [comment]
@RabbitDoge Requested changes made. Thank you.

**Review by RabbitDoge — APPROVED** [review]

**Pull request merged**
